"""concept_quizzes generation_status

Revision ID: 94cc4063d201
Revises: ad8f17b309e7
Create Date: 2026-09-14 21:27:11.929398
"""
from alembic import op
import sqlalchemy as sa


revision = '94cc4063d201'
down_revision = 'ad8f17b309e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_quizzes', sa.Column('generation_status', sa.String(length=16), server_default='ready', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_quizzes', 'generation_status')
    # ### end Alembic commands ###
