"""initial schema - akara 20 tables

Revision ID: ad8f17b309e7
Revises: 
Create Date: 2026-09-14 18:34:24.241966
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ad8f17b309e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('class_min', sa.SmallInteger(), nullable=False),
    sa.Column('class_max', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('class', sa.SmallInteger(), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('chapter_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapters_subject_number', 'chapters', ['subject_id', 'chapter_number'], unique=False)
    op.create_table('daily_activity',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_index('ix_daily_activity_user_date', 'daily_activity', ['user_id', 'date'], unique=False)
    op.create_table('language_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('native_script', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'month', name='uq_lang_req_user_lang_month')
    )
    op.create_index('ix_lang_req_month', 'language_requests', ['month'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('interest', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('data_saver_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('topic_name', sa.Text(), nullable=True),
    sa.Column('ncert_citation', sa.Text(), nullable=True),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('class', sa.SmallInteger(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('rubric', sa.Text(), nullable=True),
    sa.Column('rubric_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisite_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'order_index', name='uq_concepts_chapter_order')
    )
    op.create_index('ix_concepts_chapter', 'concepts', ['chapter_id'], unique=False)
    op.create_index('ix_concepts_subject', 'concepts', ['subject_id'], unique=False)
    op.create_table('offline_downloads',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=True),
    sa.Column('concept_count', sa.SmallInteger(), nullable=True),
    sa.Column('downloaded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('progress_percent', sa.SmallInteger(), nullable=False),
    sa.Column('est_seconds_remaining', sa.SmallInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('video_r2_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_r2_key', sa.Text(), nullable=True),
    sa.Column('audio_r2_key', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_video_id', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'lang', name='uq_concept_media_concept_lang')
    )
    op.create_index('ix_concept_media_status', 'concept_media', ['status'], unique=False)
    op.create_table('concept_quizzes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('quiz', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scene_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mentor_prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'lang', name='uq_concept_quizzes_concept_lang')
    )
    op.create_table('rubric_points',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('level_name', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('misconception', sa.Text(), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id', 'concept_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_type', sa.String(length=10), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('dur_s', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_concept', 'sessions', ['concept_id'], unique=False)
    op.create_index('ix_sessions_student_concept', 'sessions', ['student_id', 'concept_id', 'created_at'], unique=False)
    op.create_table('user_concept_mastery',
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('best_mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'concept_id')
    )
    op.create_index('ix_mastery_student_updated', 'user_concept_mastery', ['student_id', 'updated_at'], unique=False)
    op.create_table('coverage_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('rubric_point_id', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('scorer_model', sa.String(length=40), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'concept_id', 'rubric_point_id', name='uq_coverage_session_point')
    )
    op.create_index('ix_coverage_student_concept', 'coverage_points', ['student_id', 'concept_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('rubric_point_id', sa.SmallInteger(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('diagnostic_insight', sa.Text(), nullable=False),
    sa.Column('actionable_hint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_misconceptions_student_status', 'misconceptions', ['student_id', 'status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('video_render_jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('stage_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['concept_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_render_jobs_concept_lang', 'video_render_jobs', ['concept_id', 'lang', 'created_at'], unique=False)
    op.create_table('provider_costs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('render_job_id', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('est_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['render_job_id'], ['video_render_jobs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_costs_created', 'provider_costs', ['created_at'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_index', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('stt_lang', sa.String(length=20), nullable=True),
    sa.Column('conf', sa.Float(), nullable=True),
    sa.Column('stt_lat_ms', sa.Integer(), nullable=True),
    sa.Column('llm_ttft_ms', sa.Integer(), nullable=True),
    sa.Column('tts_ttfb_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turns_transcript_index', 'transcript_turns', ['transcript_id', 'turn_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_turns_transcript_index', table_name='transcript_turns')
    op.drop_table('transcript_turns')
    op.drop_index('ix_costs_created', table_name='provider_costs')
    op.drop_table('provider_costs')
    op.drop_index('ix_render_jobs_concept_lang', table_name='video_render_jobs')
    op.drop_table('video_render_jobs')
    op.drop_table('transcripts')
    op.drop_index('ix_misconceptions_student_status', table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index('ix_coverage_student_concept', table_name='coverage_points')
    op.drop_table('coverage_points')
    op.drop_index('ix_mastery_student_updated', table_name='user_concept_mastery')
    op.drop_table('user_concept_mastery')
    op.drop_index('ix_sessions_student_concept', table_name='sessions')
    op.drop_index('ix_sessions_concept', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('rubric_points')
    op.drop_table('concept_quizzes')
    op.drop_index('ix_concept_media_status', table_name='concept_media')
    op.drop_table('concept_media')
    op.drop_table('offline_downloads')
    op.drop_index('ix_concepts_subject', table_name='concepts')
    op.drop_index('ix_concepts_chapter', table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('user_preferences')
    op.drop_table('user_interests')
    op.drop_index('ix_lang_req_month', table_name='language_requests')
    op.drop_table('language_requests')
    op.drop_index('ix_daily_activity_user_date', table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index('ix_chapters_subject_number', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('users')
    op.drop_table('subjects')
    # ### end Alembic commands ###
